catalog
htmlacademy-adaptive/1913295-cat-energy-24 pull request #4
Opened 2021-12-07 17:38 UTC by Dmitrii129

white

2021-12-08 16:01 UTC, hen04 requested changes
В целом код написан хорошо, есть понимание, что является блоком, а что элементом. Нужно подтянуть еще понимание модификатора ))
И еще в макете есть страница с формами. Добавь ее, пожалуйста, в следующем коммите.

2021-12-09 15:50 UTC, Dmitrii129 commented on source/catalog.html
> +            <div class="product__box--reg-small">
<div class="product__box product--purple-small"> так?

2021-12-09 15:51 UTC, Dmitrii129 commented on source/catalog.html
> +            <div class="product__box--reg-small">
div class="product__box product--purple-small"

2021-12-09 18:51 UTC, hen04 requested changes
Дима, отнесись, пожалуйста, внимательно к разметке. 
Пока очень много моментов, которые нужно поправить. 
Посмотри материалы из прежнего курса:
https://up.htmlacademy.ru/adaptive/24/prepare/item/18
https://up.htmlacademy.ru/adaptive/24/prepare/item/19

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +        <section class="prog-param">
Не очень удачное именование класса, лучше не использовать транслит -- param, если ты хотел написать параметры, лучше использовать перевод -- options. И лучше написать не prog, а program

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +            <span class="prag-param__label">имя:*</span>
Здесь опечатка в именовании класса

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +            <p class="prog-param__subtitle">Заполните анкету, и мы подберем программу питания для вашего кота</p>
Нет тега формы. Как браузер поймет, что это все, что ниже, находится в форме?

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +            <span class="prag-param__label">вес(кг):*</span>
Здесь нужно подумать, какой тег подойдет лучше

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +                    <input type="radio" class="programm__field" name="weight-loss" checked />
Подумай, пожалуйста, для чего нужен атрибут name у радио-кнопок. Здесь ошибка. 
https://up.htmlacademy.ru/adaptive/24/prepare/item/18
https://up.htmlacademy.ru/adaptive/24/prepare/item/19

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +                    <span class="kit__box">Похудение</span>
Здесь нужно подумать, какой тег подойдет лучше

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +            <span class="contact__label">E-mail:*</span>
Здесь нужно подумать, какой тег подойдет лучше

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +            <span class="contact__label">Телефон:*</span>
Здесь нужно подумать, какой тег подойдет лучше

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +        <section class="dop">
Я бы использовала другое название для класса, можно например additional

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +        <section class="commit">
Почему класс у блока называется commit? Может быть ты хотел назвать comment?

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +        <section class="kit">
Подумай, какой тег лучше использовать вместо section. Для групп полей в форме есть специальный тег.

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +                    <span class="dop__label">Сахарозаменитель</span>
Здесь нужно подумать, какой тег подойдет лучше

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +                    <input class="visually-hidden dop__box" type="checkbox" name="wi-fi" checked />
Подумай здесь, пожалуйста, какой должен быть атрибут name у чекбоксов. Если не найдешь материалы, напиши мне, погуглим вместе

2021-12-09 18:51 UTC, hen04 commented on source/form.html
> +            <img class="page-map__image" src="../source/img/Rectangle.jpg " width="320" height="362" alt="Карта">
А почему карта называется Rectagnle? У тебя все изображения называются с маленькой буквы, а здесь с большой, нужно придерживаться единого стиля в именовании файлов. Нужно поправить на всех страницах, если там тоже такое название.

2021-12-11 16:11 UTC, hen04 commented on source/form.html
> +                            <span class="kit__box">Похудение</span>
Здесь лучше подойдет другой тег, подумай, что лучше подходит для инпутов

2021-12-11 16:11 UTC, hen04 commented on source/form.html
> +                    <label class="contact tel">
тааак, тут кажется, что-то напутано. У тебя уже есть блок contact, здесь должен быть элемент. А tel -- это для чего?

2021-12-11 16:11 UTC, hen04 commented on source/form.html
> +                <fieldset class="commit">
Дима, а почему класс называется commit? По смыслу должно быть что-то похожее на Комментарий

2021-12-11 16:11 UTC, hen04 commented on source/form.html
> +                <fieldset class="dop">
Посмотри комментарий к предыдущему коммиту, я написала подробно, что нельзя называть класс транслитерацией, да еще и так сокращать.

2021-12-11 16:12 UTC, merged